"use strict";

/**
 * Composable for exporting conversation transcript + sources as a markdown file.
 * Reads conversationHistory, sources, and persona from the session store.
 */
export function useExportTranscript() {
    const sessionStore = useSessionStore();
    const { conversationHistory, sources, persona } = storeToRefs(sessionStore);

    const canExport = computed(() => conversationHistory.value.length > 0);

    function generateMarkdown(): string {
        const personaName = persona.value?.name || "Unknown";
        const date = new Date().toLocaleDateString();
        let md = `# DeadTalk — Conversation with ${personaName}\n`;
        md += `**Date:** ${date}\n\n`;
        md += `## Transcript\n\n`;

        for (const entry of conversationHistory.value) {
            const speaker = entry.role === "user" ? "You" : personaName;
            const cleanText = entry.text
                .replace(/\[[^\]]*\]/g, "")
                .replace(/\s{2,}/g, " ")
                .trim();
            md += `**${speaker}:** ${cleanText}\n\n`;
        }

        if (sources.value.length > 0) {
            md += `## Sources\n\n`;
            for (const src of sources.value) {
                md += `- [${src.title}](${src.url})\n`;
                if (src.snippet) {
                    md += `  ${src.snippet.substring(0, 150)}\n`;
                }
                md += `\n`;
            }
        }

        md += `---\n*Generated by DeadTalk — ElevenHacks 2026*\n`;
        return md;
    }

    function downloadTranscript(): void {
        const md = generateMarkdown();
        const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        const safeName = (persona.value?.name || "conversation").replace(/\s+/g, "-").toLowerCase();
        a.download = `deadtalk-${safeName}-${Date.now()}.md`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    }

    return { downloadTranscript, canExport };
}
